version: '3.9'

services:
  server:
    container_name: api-docker
    # network_mode: "host"
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      network: "host"
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.main:app --reload
    ports:
      - "8000:8000"
    stop_signal: SIGINT
