version: '3.9'

services:
  server:
    container_name: api
    network_mode: "host"
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      network: "host"
    volumes:
      - ./backend/:/backend/
    ports:
      - "8000:8000"
    depends_on:
      - db
    stop_signal: SIGINT
