version: '3.9'

services:
  server:
    container_name: api
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/:/backend/
    stop_signal: SIGINT
    depends_on:
      - db

  db:
    image: postgres:16-bookworm
    container_name: pg-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

volumes:
    postgres_data:
